Добавил обработку ошибок
alex-karo/oldranger-front pull request #104
Opened 2020-04-10 13:40 UTC by anatolykobzisty

2020-04-10 13:51 UTC, anatolykobzisty commented
Добавил пока только для двух запросов logIn и logOut

2020-04-12 12:04 UTC, veli-aliev requested changes

2020-04-12 12:04 UTC, veli-aliev commented on src/App.jsx
> +        }
Нужно проверять в общем интерсепторе, а не дублировать в каждом методе. Смотри axios interceptors

2020-04-12 12:04 UTC, veli-aliev commented on src/components/Login.jsx
> +        showMessageNetError(error);
Нужно проверять в общем интерсепторе, а не дублировать в каждом методе. Смотри axios interceptors

2020-04-13 12:54 UTC, veli-aliev requested changes
Не вижу фиксов

2020-04-14 15:23 UTC, veli-aliev approved these changes

2020-04-15 20:23 UTC, merged