wrap links in chat message with tag
alex-karo/oldranger-front pull request #107
Opened 2020-04-13 17:26 UTC by cvcd005

Добавил обертку ссылок в текстовых сообщениях в тег <a>
Шаблон регэкспа 
Это ссылки
    http://www.foufos.gr
    https://www.foufos.gr
    http://foufos.gr
    http://www.foufos.gr/kino
    http://werer.gr
    http://t.co
 
Это не ссылки
   www.foufos.gr
    www.foufos
    www.foufos-.gr
    foufos.gr
    http:www.foufos.ru
    http://foufos
    www.mp3#.com

2020-04-15 20:25 UTC, veli-aliev requested changes

2020-04-15 20:25 UTC, veli-aliev commented on src/components/Chat/Chat.jsx
> +      ) : (
Почему проверяется четность индекса? Что делает режексп сверху?

2020-04-16 05:40 UTC, cvcd005 commented on src/components/Chat/Chat.jsx
> +      ) : (
Строка сообщения
 'зацени ссылку http://www.google.com' переделываю в массив
 ['зацени ссылку ', 'http://www.google.com''] 
Если сообщение 'http://www.google.com' то получается массив
 ['', 'http://www.google.com', ''] 
Если сообщение '"Это просто сообщение без ссылок' получается массив"
 ['Это просто сообщение без ссылок' получается массив']
То есть спилт с  regexp делает массив, где каждый нечетный индекс это ссылка

2020-04-21 08:15 UTC, veli-aliev approved these changes

2020-04-21 08:16 UTC, merged