Add comment image
alex-karo/oldranger-front pull request #197
Opened 2020-06-30 07:35 UTC by alexey-oblomov

Возможность комментировать изображения в галерее

2020-07-03 07:22 UTC, veli-aliev requested changes

2020-07-03 07:22 UTC, veli-aliev commented on src/components/Profile/Albums/ModalPhoto.jsx
> +}
Вынести из компонента в папку utils или helpers

2020-07-03 07:22 UTC, veli-aliev commented on src/components/Profile/Albums/Album.jsx
Удалить комментарии

2020-07-03 09:54 UTC, alexey-oblomov reviewed
Замечания устранены

2020-07-20 11:50 UTC, veli-aliev submitted a review, later dismissed

2020-07-23 13:13 UTC, merged