Tree
alex-karo/oldranger-front pull request #221
Opened 2020-08-10 16:53 UTC by waleron07

2020-08-20 12:55 UTC, veli-aliev requested changes

2020-08-20 12:55 UTC, veli-aliev commented on package.json
> +    "react-dnd": "^11.1.3",
либа используется?

2020-08-20 12:55 UTC, veli-aliev commented on package.json
> +    "@babel/plugin-proposal-optional-chaining": "^7.10.4",
разве реактовский бабель по умолчанию не поддерживает опшнл чейнинг?

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTagsEdit.jsx
> +  };
вынести из компонента в utils, дать менее абстрактное название

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTagsEdit.jsx
> +  };
Вынести в utils. Почему решили не менять структуру данных на беке, а конвертировать на фронте?

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTagsEdit.jsx
>      fetchTags();
зачем сфетчивать все дерево заново?

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTagsEdit.jsx
> +    fetchTags();
зачем сфетчивать все дерево заново?

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTree.jsx
> +    const nevTag = {
опечатка в названии

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTree.jsx
> +      children.map((el, indexEl) => normalizeData(el, id, indexEl, acc));
результат мапа никуда не присвоен, зачем его использовать?

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTree.jsx
> +  };
вынести в utils

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTree.jsx
> +  }, [props]);
каждый ререндер (даже тот, который будет происходить из-за передачи не мемоизированных колбеков  handleTagsSubmit и handleCancel) будет вызывать эту функцию. Это точно задуманное поведение?

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTree.jsx
> +  const fetchTags = () => {
Почему функция называется fetch, если она ничего не фетчит?

2020-08-20 12:55 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTree.jsx
> +  const renderComponents = tags => (
Название ни о чем не говорит

2020-08-20 12:55 UTC, veli-aliev commented on src/serverQueries/index.jsx
> +    return res;
зачем нужна промежуточная переменная? Почему сразу не вернуть результат аксиоса?

2020-08-20 12:55 UTC, veli-aliev commented on src/serverQueries/index.jsx
> +    return res;
зачем нужна промежуточная переменная? Почему сразу не вернуть результат аксиоса?

2020-08-21 08:32 UTC, waleron07 commented on package.json
> +    "react-dnd": "^11.1.3",
используется. если убрать вот лог

2020-08-21 08:32 UTC, waleron07 commented on package.json
> +    "react-dnd": "^11.1.3",
./node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js
Module not found: Can't resolve 'react-dnd' in '/home/waleron/Рабочий стол/projectJM/tree/oldranger-front/node_modules/frontend-collective-react-dnd-scrollzone/lib'

2020-08-21 08:39 UTC, waleron07 commented on src/components/AdminPanel/ArticlesTagsEdit.jsx
> +  };
если менять структуру вообщем на беке, то часть данных (а именно структуры) влияют на остальную часть проекта, то пришлось бы беку очень много поработать, и мы посчитали что лучше менять на фронте чем переберать потом пол проекта

2020-08-21 10:02 UTC, waleron07 commented on src/components/AdminPanel/ArticlesTree.jsx
> +  }, [props]);
переправил так

2020-08-21 10:02 UTC, waleron07 commented on src/components/AdminPanel/ArticlesTree.jsx
> +  }, [props]);
useEffect(() => {
    transformationTree();
  }, [dataTags]);

2020-08-21 10:02 UTC, waleron07 commented on src/components/AdminPanel/ArticlesTree.jsx
> +  }, [props]);
вызыво функции происходит только если меняется пропсы дерева

2020-08-29 14:43 UTC, waleron07 commented on src/components/AdminPanel/ArticlesTree.jsx
> +    const nevTag = {
если ты про  idParent то его исправил уже, функция перенесена в utils 61 строка и название функции parseTags

2020-09-02 10:30 UTC, veli-aliev commented on src/components/AdminPanel/ArticlesTree.jsx
> +    const nevTag = {
я про nevTag

2020-09-02 10:31 UTC, veli-aliev commented
Вмерживаю с комментами, нужно пофиксить

2020-09-02 10:31 UTC, veli-aliev approved these changes

2020-09-02 10:31 UTC, merged