fix: re-rendering on every input
alex-karo/oldranger-front pull request #230
Opened 2020-09-02 19:59 UTC by Azkvns

Упрощена логика формы, добавлена валидация, исключены лишние ререндеры

2020-09-10 15:48 UTC, veli-aliev requested changes

2020-09-10 15:48 UTC, veli-aliev commented on src/components/Profile/Albums/ModalPhoto.jsx
> +      validationSchema={Yup.object({ text: Yup.string().required('Введите текст комментария') })}
Зачем формировать validationSchema при каждом рендере? Вынеси из компонента в константу

2020-09-10 16:05 UTC, Azkvns commented on src/components/Profile/Albums/ModalPhoto.jsx
> +      validationSchema={Yup.object({ text: Yup.string().required('Введите текст комментария') })}
Готово

2020-09-18 16:15 UTC, veli-aliev approved these changes

2020-09-18 16:15 UTC, merged