Feat/add form validation on create comment in topics
alex-karo/oldranger-front pull request #234
Opened 2020-09-05 15:01 UTC by Azkvns

2020-09-14 19:48 UTC, veli-aliev approved these changes

2020-09-14 19:50 UTC, veli-aliev requested changes

2020-09-14 19:50 UTC, veli-aliev commented on src/components/Topic/TopicPage.jsx
> +      text: messageText.length ? messageText : '<br>',
зачем здесь br?

2020-09-14 19:50 UTC, veli-aliev commented on src/components/Topic/TopicReplyEditor.jsx
> +// Этот костыль подчищает за ReactQuill, который оставляет
есть какая-то ссылка на issue с этим багом в ReactQuill?

2020-09-15 15:18 UTC, Azkvns commented on src/components/Topic/TopicPage.jsx
> +      text: messageText.length ? messageText : '<br>',
Костыль
бэк ожидает не пустое сообщение, а задача была сделать возможным отправку сообщений без текста, но с фото
Как альтернатива, можно попросить поменять бэк

2020-09-17 06:53 UTC, Azkvns commented on src/components/Topic/TopicReplyEditor.jsx
> +// Этот костыль подчищает за ReactQuill, который оставляет
Нет, просмотрел все issue, но такого не нашёл

2020-09-17 07:59 UTC, Azkvns commented on src/components/Topic/TopicPage.jsx
> +      text: messageText.length ? messageText : '<br>',
Создал таску для бэка

2020-09-29 17:05 UTC, veli-aliev approved these changes

2020-09-29 17:05 UTC, merged