refactor: albums components moved and changed
alex-karo/oldranger-front pull request #235
Opened 2020-09-09 17:06 UTC by Azkvns

Компоненты альбомов перемещены из профиля на верхний уровень, изменен их роутинг, добавлены изменения в ModalPhoto из предыдущего пул реквеста

2020-09-14 19:53 UTC, veli-aliev requested changes

2020-09-14 19:53 UTC, veli-aliev commented on src/components/Albums/Album.jsx
> +        <Context.Consumer>
Используй useContext в функциональном компоненте

2020-09-14 19:53 UTC, veli-aliev commented on src/components/Albums/ModalPhoto.jsx
> +      validationSchema={Yup.object({ text: Yup.string().required('Введите текст комментария') })}
вынести yup schema из компонента. Сейчас ты генерируешь ее заново при каждом рендере

2020-09-16 12:59 UTC, Azkvns commented on src/components/Albums/Album.jsx
> +        <Context.Consumer>
Готово

2020-09-16 12:59 UTC, Azkvns commented on src/components/Albums/ModalPhoto.jsx
> +      validationSchema={Yup.object({ text: Yup.string().required('Введите текст комментария') })}
Готово

2020-09-18 16:16 UTC, veli-aliev approved these changes

2020-09-18 16:43 UTC, merged