Albums
alex-karo/oldranger-front pull request #30
Opened 2020-02-04 14:34 UTC by archi7779

Добавил:
Альбомы создать\удалить\смотреть
Фото добавить\удалить

2020-02-04 14:51 UTC, alex-karo requested changes

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +  LoadAlboms = async () => {
camelCase (остальные функции тоже)

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +const StyledAlbomCard = styled.div`
Albom -> Album (везде, включая имена файлов)

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +              Создать новый альбом
Почему дублируется в коде?

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +      alert("u need to enter albom's title");
По русски, у нас русскоязычный сайт, давай вместо алерта возьмем компонент анта
https://ant.design/components/message/

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +  .StyledAlbomCard-albomTitle{
Зачем смешивать подходы стилизованных компонентов и классов?
Вынеси как стилизованные компоненты

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +      console.log(error.response);
console.log -> console.error
И давай выведем пользователю сообщение, что у нас что-то пошло не так
https://ant.design/components/message/

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +      console.log(error);
the same ^^

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Alboms.jsx
> +              <p className="StyledAlbomCard-albomTitle">{albom.title}</p>
Это не параграф текста

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Albom.jsx
> +            {uploading ? 'Загружаем' : 'Добавить Фотографии в альбом'}
А, если в процессе загрузки, мы попробуем загрузить еще один файл - как отработает?

2020-02-04 14:51 UTC, alex-karo commented on src/components/Profile/Albom.jsx
> +                <Icon type="upload" /> Перетащите сюда или выберите фотографии
Зачем дублирование в коде?

2020-02-06 14:47 UTC, archi7779 commented on src/components/Profile/Alboms.jsx
> +  LoadAlboms = async () => {
++

2020-02-06 14:47 UTC, archi7779 commented on src/components/Profile/Alboms.jsx
> +const StyledAlbomCard = styled.div`
++

2020-02-07 15:27 UTC, alex-karo requested changes

2020-02-07 15:27 UTC, alex-karo commented on package.json
> +    "array-move": "^2.2.1",
Что делает этот пакет?

2020-02-07 15:27 UTC, alex-karo commented on src/components/Profile/Album.jsx
> +      photoTempUlr: 'http://localhost:8888/img/chat/',
Этот параметр меняется в ходе жизни компонента?

2020-02-07 15:27 UTC, alex-karo commented on src/components/Profile/Album.jsx
> +  handleUpload = async () => {
Неконсистетное именомение, то onAction, то handleAction, то вообще без
Давай остановимся на handle

2020-02-07 15:27 UTC, alex-karo commented on src/components/Profile/Album.jsx
> +          <Upload {...uploadProps} disabled={uploading}>
Вынеси функционал загрузки в отдельный компонент - этот и так слишком разросся

2020-02-07 15:30 UTC, archi7779 commented on package.json
> +    "array-move": "^2.2.1",
там функция которая меняет положение в массиве

2020-02-07 15:30 UTC, archi7779 commented on src/components/Profile/Album.jsx
> +      photoTempUlr: 'http://localhost:8888/img/chat/',
нет, но используется в нескольких местах

2020-02-07 15:35 UTC, alex-karo commented on src/components/Profile/Album.jsx
> +      photoTempUlr: 'http://localhost:8888/img/chat/',
Если не меняется - ему в стейте не место

2020-02-07 16:00 UTC, merged