Chat
alex-karo/oldranger-front pull request #32
Opened 2020-02-07 16:34 UTC by stanza24

Created chat page

2020-02-07 17:16 UTC, alex-karo requested changes

2020-02-07 17:16 UTC, alex-karo commented on package.json
> +    "deploy": "gh-pages -d build"
Куда дел линтер и прекоммит хук?

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/css/Chat.css
> +.chat {
Перенести в styled components весь css

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +    const { data } = await axios.post(`${url}/api/chat/image`, formData, {
Сетевые http запросы вынеси в файлик со всеми сетевыми запросами (кажется, там что-то такое уже было)
Вебсокет оставь тут

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +import _ from 'lodash';
Разве lodash есть в dependencies?

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +                    {messages.slice(-19).map(msg => this.drawMessage(msg))}
Что такое slice(-19) ?

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +          key={_.uniqueId()}
У сообщений нет адекватного айдишника?

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +    const firstMessage = document.querySelector('.message-list li:nth-child(2)');
Эм... До второй элемент? Почему?
А если верстка изменится - этот селектор сломается?

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +    sendMessage(message, image, replyTo);
Этот запрос может не пройти? Если он не пройдет - сообщение тоже затрется?

2020-02-07 17:16 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +        sendButton.click();
Кликаем по кнопку через дом? Почему мы сразу не можем обработать хэндлер?

2020-02-10 06:17 UTC, stanza24 commented on src/components/Chat/Chat.jsx
> +    sendMessage(message, image, replyTo);
ws не возвращает ошибок, так что сообщение в любом случае уходит

2020-02-10 06:17 UTC, stanza24 commented on src/components/Chat/Chat.jsx
> +                    {messages.slice(-19).map(msg => this.drawMessage(msg))}
19 последних сообщений

2020-02-10 07:18 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +                    {messages.slice(-19).map(msg => this.drawMessage(msg))}
1) bad pattern "magic numbers" - не надо так
2) А как читать более ранние сообщения?

2020-02-10 07:18 UTC, alex-karo commented on src/components/Chat/Chat.jsx
> +    sendMessage(message, image, replyTo);
Что происходит, если нет связи?

2020-02-10 08:50 UTC, stanza24 commented on src/components/Chat/Chat.jsx
> +                    {messages.slice(-19).map(msg => this.drawMessage(msg))}
все понял ошибку

2020-02-10 08:50 UTC, stanza24 commented on src/components/Chat/Chat.jsx
> +    sendMessage(message, image, replyTo);
коннекта не происходит

2020-02-10 11:59 UTC, closed without merging