Fix user blocking
alex-karo/oldranger-front pull request #75
Opened 2020-03-22 11:50 UTC by EvgeniiT

Исправлен разбан юзеров. Добавлен запрос unblocking.

2020-03-23 19:11 UTC, veli-aliev requested changes

2020-03-23 19:11 UTC, veli-aliev commented on src/components/AdminMenu/index.jsx
> +
Для того, чтобы поменять флаг, ты фетчишь целую сущность с сервера. Не лучшая практика. + если вы на основе этого как-то меняете интерфейс, то юзер заскучает, пока цепочка из двух последовательных запросов закончится) Лучшей практикой будет, если ты вручную изменишь это поле по клику, затем отправишь запрос на анбан, а если в запросе на анбан вылетит ошибка, то вернешь поле в исходное состояние. При этом фетчить юзера не нужно вообще

2020-03-23 19:11 UTC, veli-aliev commented on src/serverQueries/index.jsx
> +    const res = await axios.post('/api/admin/unblocking', { id });
1) URL'ы лучше выносить в константу (URLS = { UNBLOCKING: '/admin/unblocking' }), но тут уже по всему проекту пошли magic strings, поэтому это больше как рекомендация. Можешь начать первым и вынести урл в константу. 

2) "api" лучше вынести в базовый урл бекенда, потому что бывает такое, что выходит новая версия API и ссылка меняется, к примеру, на api/v2. В этом случае придется по всему проекту менять api на api/v2 вместо того, чтобы заменить в одном месте. Да и не особо удобно и нецелесообразно писать api каждый раз

Второй пункт сейчас менять придется по всему проекту, поэтому это рекомендация на будущее, можешь не фиксить. Первый по желанию, но лучше начинать делать правильно сразу

2020-03-23 19:11 UTC, veli-aliev commented on src/serverQueries/index.jsx
> +    return res.data;
Если везде пишется res.data, то было бы проще использовать axios interceptor, который автоматически достает data из запроса. Рекомендация на будущее, можешь не фиксить

2020-03-26 08:55 UTC, EvgeniiT commented on src/components/AdminMenu/index.jsx
> +
Пофиксил

2020-03-26 09:14 UTC, EvgeniiT commented on src/serverQueries/index.jsx
> +    const res = await axios.post('/api/admin/unblocking', { id });
Давай пока не будем исправлять, можно сделать карточку на рефакторинг.

2020-03-26 09:15 UTC, EvgeniiT commented on src/serverQueries/index.jsx
> +    return res.data;
Тоже можно добавить в карточку на рефакторинг.

2020-03-26 16:59 UTC, veli-aliev approved these changes

2020-03-26 16:59 UTC, merged