change articles menu tags
alex-karo/oldranger-front pull request #97
Opened 2020-04-06 08:57 UTC by cvcd005

Изменил отображение меню тегов 
![changes](https://user-images.githubusercontent.com/43474933/78541020-a9f41b80-77fd-11ea-9749-2513741c1a23.png)
Изменил функционал отображения активного тега(Раньше отображались только самые нижние)
Добавил функционал отображения активного тега после перезагрузки страницы
P.S. добавил свой визуальный компонент, так как встроенными элементами antd не смог нормально сделать

2020-04-06 20:16 UTC, veli-aliev requested changes

2020-04-06 20:16 UTC, veli-aliev commented on src/components/Articles/TagsMenu/TagsMenu.jsx
> +    const hierarchy = String(href[href.length - 1]);
Нужный параметр урла всегда будет последним? А если нет?

2020-04-06 20:16 UTC, veli-aliev commented on src/components/Articles/styled/index.js
> +export const MyTagsItem = styled.p`
Зачем приставка My перед названием компонента? Есть пересечение с какой-то библиотекой?

2020-04-07 06:17 UTC, cvcd005 commented on src/components/Articles/TagsMenu/TagsMenu.jsx
> +    const hierarchy = String(href[href.length - 1]);
Думаю маловероятно) Делал под текущие эндпоинты. Если же ввести кракозябру то меню тегов не сломается, просто не будет отображаться активным какой-то тег.
!!!!!НО нашел проблему в другом компоненте при вводе некоректных значений. Починю тот компонент в другом комите

2020-04-07 06:17 UTC, cvcd005 commented on src/components/Articles/styled/index.js
> +export const MyTagsItem = styled.p`
Название компонента делал чтобы точно понять, что это самописный компонент) Если нужно могу переименовать просто в TagsItem)

2020-04-07 13:22 UTC, cvcd005 commented
Переименовал компонент в TagsItem

2020-04-07 13:26 UTC, veli-aliev requested changes

2020-04-07 13:26 UTC, veli-aliev commented on src/components/Articles/TagsMenu/TagsMenu.jsx
> +    const hierarchy = String(href[href.length - 1]);
Зачем вообще обращаться по индексу, если можно найти нужный параметр по его названию?

2020-04-07 13:28 UTC, veli-aliev commented on src/components/Articles/styled/index.js
> +export const MyTagsItem = styled.p`
И так можно понять по импортам) Да и не особо важно это понимать, если ты не собираешься редактировать компонент. А если собираешься, то и так увидишь. По крайней мере я не видел, чтобы так делали когда-нибудь, выглядит излишним. Так делают тогда, когда твое название пересекается с названием компонента из библиотеки

2020-04-08 07:04 UTC, cvcd005 commented on src/components/Articles/TagsMenu/TagsMenu.jsx
> +    const hierarchy = String(href[href.length - 1]);
Парсинг сделал для проверки если в урл добавили теги руками(маловероятно но все же) тогда get запрос уйдет, а нужный тег не подстветится
И основное, есть кнопка СТАТЬИ - это отдельный компонент, нажатие на эту кнопку возвращает список всех статей все теги  при этом выключаются, урл очищается от query string
Поэтому, чтобы компонент МЕНЮ ТЕГОВ узнал, что нажата кнопка СТАТЬИ я монитрирую урл и при его изменении подсвечиваю нужный тег( в зависимости от квери стринг)
Как по другому сделать я не знаю)

2020-04-10 05:54 UTC, cvcd005 commented
Добавил хук для query string Теперь атрибуты ищутся по ключу tags
Добавил проверку на ввод плохих тегов

2020-04-11 12:55 UTC, veli-aliev requested changes

2020-04-11 12:55 UTC, veli-aliev commented on src/hooks/useQuery.jsx
> +
Возвращай весь объект, неудобное API хука. Если мне нужно будет 3 параметра, трижды вызывать хук и выполнять эти вычисления?

2020-04-11 12:59 UTC, veli-aliev commented on src/hooks/useQuery.jsx
> +
Вместо прокидывания location внутрь хука используй хук useLocation: https://reacttraining.com/react-router/web/api/Hooks/uselocation

Хук будет самостоятельным и его будет проще использовать

2020-04-12 11:18 UTC, cvcd005 commented
Добавил useLocation 
изменил useQuery возвращает весь объект

2020-04-12 11:51 UTC, veli-aliev approved these changes

2020-04-12 11:51 UTC, merged