add check when enter bad tag
alex-karo/oldranger-front pull request #99
Opened 2020-04-07 07:09 UTC by cvcd005

Добавлена проверка ввода плохих тегов у статей
![result](https://user-images.githubusercontent.com/43474933/78640083-cd7b9c80-78b7-11ea-810d-a49ee6b4ef82.png)

2020-04-07 13:33 UTC, veli-aliev requested changes

2020-04-07 13:33 UTC, veli-aliev commented on src/components/Articles/ArticlesByTag.jsx
> +      const tagsArr = tmp[tmp.length - 1].split('_');
tmp - название ни о чем не говорит, назови переменную по ее содержимому
Обращайся к query параметру не по индексу, а по названию

2020-04-07 13:33 UTC, veli-aliev commented on src/components/Articles/ArticlesByTag.jsx
> +          setArticles(el.content.reverse());
Почему приходится делать reverse() на ответе с бекенда? Неудачное API или в разных местах нужен разный порядок статей?

2020-04-07 15:32 UTC, cvcd005 commented on src/components/Articles/ArticlesByTag.jsx
> +          setArticles(el.content.reverse());
Да, с бека приходит по разному

2020-04-08 06:57 UTC, cvcd005 commented on src/components/Articles/ArticlesByTag.jsx
> +      const tagsArr = tmp[tmp.length - 1].split('_');
Что значит обращаться к query параметру не по индексу?)

2020-04-10 05:57 UTC, cvcd005 commented
Функционал добавлен в пулреквет #97

2020-04-10 05:57 UTC, closed without merging